config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'seriees', to: 'seriees#index'
  get 'seriees/new'
  get 'documentary_films', to: 'documentary_films#index'
  get 'documentary_films/new'
  get 'movies', to: 'movies#index'
  get 'movies/new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  post 'seriees', to: "seriees#create"
  post 'movies', to: "movies#create"
  post 'documentary_films', to: "documentary_films#create"
  # Defines the root path route ("/")
  root "home#index"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/documentary_film.rb
class DocumentaryFilm < ApplicationRecord

    validates :name, presence: true
    validates :synopsis, presence: true
    validates :director, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord

    validates :name, presence: true
    validates :synopsis, presence: true
    validates :director, presence: true
end

app/models/seriee.rb
class Seriee < ApplicationRecord

    validates :name, presence: true
    validates :synopsis, presence: true
    validates :director, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/documentary_films_controller.rb
class DocumentaryFilmsController < ApplicationController
  def index
    @documentary_films= DocumentaryFilm.all
  end

  def new
    @documentary_film = DocumentaryFilm.new
  end

  def create
    @documentary_film = DocumentaryFilm.new(documentary_film_params)

    if @documentary_film.save
      redirect_to documentary_films_path
    else
      render :new
    end
  end


  private

  def documentary_film_params
    params.require(:documentary_film).permit(:name, :synopsis, :director)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies= Movie.all
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)

    if @movie.save
      redirect_to movies_path
    else
      render :new
    end
  end


  private

  def movie_params
    params.require(:movie).permit(:name, :synopsis, :director)
  end
end

app/controllers/seriees_controller.rb
class SerieesController < ApplicationController
  def index
    @seriees = Seriee.all
  end

  def new
    @seriee = Seriee.new
  end

  def create
    @seriee = Seriee.new(seriee_params)

    if @seriee.save
      redirect_to seriees_path
    else
      render :new
    end
  end


  private

  def seriee_params
    params.require(:seriee).permit(:name, :synopsis, :director)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documentary_films_helper.rb
module DocumentaryFilmsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/seriees_helper.rb
module SerieesHelper
end

app/views/documentary_films/index.html.erb
<h1>Listado de Documentales</h1>
<br>
<br>

<div>
    <%= link_to "Agregar un nuevo Documental", documentary_films_new_path, class: "btn btn-dark"%>
</div>

<% @documentary_films.each do |movie| %>
    <h2>Nombre Documental: <%= movie.name%></h2>
    <p>Sinopsis del Documental: <%= movie.synopsis%></p>
    <p>Director del Documental: <%= movie.director%></p>
<% end %>

app/views/documentary_films/new.html.erb
<h1 class="text-center">Crear Documentales</h1>
<br>

<div class= "d-flex justify-content-center">
    <div class= "card col-6">
        <%= form_with model: @documentary_film, method: :post do |form|%>
            <div class="boder p-5 shadow">
                <div class="mb-3">
                    <%= form.label :name, "Nombre del Documental:", class:"form-label"%>
                    <%= form.text_field :name, class:"form-control" %>
                </div>
                <div class="mb-3">
                    <%= form.label :synopsis, "Synopsis:", class:"form-label"%>
                    <%= form.text_field :synopsis, class:"form-control" %>
                </div>
                <div class="mb-3">
                    <%= form.label :director, "Nombre Director:", class:"form-label"%>
                    <%= form.text_field :director, class:"form-control" %>
                </div>
                <div class="text-center">
                    <%= form.submit "Enviar", class: "btn btn-dark"%>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/home/index.html.erb
<div class="container">
  <h1 class="mt-5 mb-4 text-center">Bienvenido</h1>
  
  <div class="row">
    <div class="col-md-4">
      <div class="card mb-4">
        <img class="card-img-top" alt="Películas" width="300" height="300" src="/assets/film.jpg" />
        <div class="card-body">
          <h5 class="card-title">Películas</h5>
          <p class="card-text">Explora nuestras películas</p>
          <%= link_to "Ver mas", movies_path, class: "btn btn-dark"%>
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <div class="card mb-4">
        <img class="card-img-top" alt="Series" width="300" height="300" src="/assets/serie.jpg" />
        <div class="card-body">
          <h5 class="card-title">Series</h5>
          <p class="card-text">Descubre nuestras series</p>
          <%= link_to "Ver mas", seriees_path, class: "btn btn-dark"%>
          
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <div class="card mb-4">
        <img class="card-img-top" alt="Documentales" width="300" height="300" src="/assets/documental.jfif" />
        <div class="card-body">
          <h5 class="card-title">Documentales</h5>
          <p class="card-text">Explora nuestros documentales</p>

          <%= link_to "Ver mas", documentary_films_path, class: "btn btn-dark"%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlmacenaDatos</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
      <div class="container-fluid">
        <%= link_to 'Home',  root_path, class:"navbar-brand"%>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <%= link_to "Movies", movies_new_path, class:"nav-link"%>
            <%= link_to "Series", seriees_new_path, class:"nav-link"%>
            <%= link_to "Documentary Film", documentary_films_new_path, class:"nav-link"%>
          </div>
        </div>
      </div>
    </nav>
    <div class= "container">
      <%= yield %>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>
  </body>
</html>

app/views/movies/index.html.erb
<h1>Listado de Movies</h1>
<br>
<br>

<div>
    <%= link_to "Agregar una nueva pelicula", movies_new_path, class: "btn btn-dark"%>
</div>

<% @movies.each do |movie| %>
    <h2>Nombre Pelicula: <%= movie.name%></h2>
    <p>Sinopsis de la pelicula: <%= movie.synopsis%></p>
    <p>Director de la Pelicula: <%= movie.director%></p>
<% end %>

app/views/movies/new.html.erb
<h1 class="text-center">Crear Peliculas</h1>
<br>

<div class= "d-flex justify-content-center">
    <div class= "card col-6">
        <%= form_with model: @movie, method: :post do |form|%>
            <div class="boder p-5 shadow">
                <div class="mb-3">
                    <%= form.label :name, "Nombre de la Pelicula:", class:"form-label"%>
                    <%= form.text_field :name, class:"form-control" %>
                </div>
                <div class="mb-3">
                    <%= form.label :synopsis, "Synopsis:", class:"form-label"%>
                    <%= form.text_field :synopsis, class:"form-control" %>
                </div>
                <div class="mb-3">
                    <%= form.label :director, "Nombre Director:", class:"form-label"%>
                    <%= form.text_field :director, class:"form-control" %>
                </div>
                <div class="text-center">
                    <%= form.submit "Enviar", class: "btn btn-dark"%>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/seriees/index.html.erb
<h1>Listado de Series</h1>
<br>
<br>

<div>
    <%= link_to "Agregar una nueva Serie", seriees_new_path, class: "btn btn-dark"%>
</div>

<% @seriees.each do |serie| %>
    <h2>Nombre de la Serie: <%= serie.name%></h2>
    <p>Sinopsis de la Serie: <%= serie.synopsis%></p>
    <p>Director de la Serie: <%= serie.director%></p>
<% end %>

app/views/seriees/new.html.erb
<h1 class="text-center">Crear Series</h1>
<br>

<div class= "d-flex justify-content-center">
    <div class= "card col-6">
        <%= form_with model: @seriee, method: :post do |form|%>
            <div class="boder p-5 shadow">
                <div class="mb-3">
                    <%= form.label :name, "Nombre de la Serie:", class:"form-label"%>
                    <%= form.text_field :name, class:"form-control" %>
                </div>
                <div class="mb-3">
                    <%= form.label :synopsis, "Synopsis:", class:"form-label"%>
                    <%= form.text_field :synopsis, class:"form-control" %>
                </div>
                <div class="mb-3">
                    <%= form.label :director, "Nombre Director:", class:"form-label"%>
                    <%= form.text_field :director, class:"form-control" %>
                </div>
                <div class="text-center">
                    <%= form.submit "Enviar", class: "btn btn-dark"%>
                </div>
            </div>
        <% end %>
    </div>
</div>